import {PoisonResistance, ParalysisResistance, SleepResistance, StunResistance, MuckResistance, BlastResistance, BleedResistance, IronSkin, Earplugs, Windproof, TremorResistance, Dungmaster, EffluvialExpert, HeatGuard, AttackBoost, DefenseBoost, HealthBoost, RecoveryUp, RecoverySpeed, FireResistance, WaterResistance, IceResistance, ThunderResistance, DragonResistance, BlightResistance, FireAttack, WaterAttack, IceAttack, ThunderAttack, DragonAttack, PoisonAttack, ParalysisAttack, SleepAttack, BlastAttack, NormalShots, PiercingShots, SpreadPowerShots, FreeElemAmmoUp, CritEye, CritBoost, WeaknessExploit, Focus, PowerProlonger, Handicraft, CritDraw, Partbreaker, Slugger, StaminaThief, MasterMounter, Airborne, LatentPower, Agitator, PeakPerformance, Heroics, Fortify, Resentment, Resuscitate, HornMaestro, CapacityBoost, SpecialAmmoBoost, Artillery, HeavyArtillery, MarathonRunner, Constitution, LeapOfFaith, StaminaSurge, HungerResistance, EvadeWindow, EvadeExtender, Guard, QuickSheath, Widerange, ItemProlonger, FreeMeal, SpeedEating, SpeedSharpening, Bombardier, Mushroomancer, MasterFisher, ProTransporter, MasterGatherer, HoneyHunter, CarvingPro, DivineBlessing, PalicoRally, Botanist, Geologist, MaxMight, SlingerCapacity, Stealth, FlinchFree, ScoutFlyRangeUp, SpeedCrawler, JumpMaster, SurvivalExp, AquaticMob, CliffHanger, Blindsider, Scholar, Entomologist, EffluviaResistance, Scenthound, ForagerLuck, Detector, BbqMaster, ToolSpecialist, AffinitySliding, Intimidator, HastenRecovery, SuperRecovery, PoisonDurationUp, Adrenaline, StaminaCapUp, CritElement, MindEye, Bludgeoner, NonElementalBoost, CaptureMaster, GuardUp, Guts, MasterTouch, NullWind, RazorSharp, CritStatus, GoodLuck, BowChargePlus, PunishingDraw, ProtectivePolish, PoisonFunc, ParaFunc, SleepFunc, BlastFunc, EldersealBoost, GreatLuck, CarvingMaster, ElementalAirborne, IgniIntensity
} from 'src/exports/SkillIconExports'


const skills = [PoisonResistance, ParalysisResistance, SleepResistance, StunResistance, MuckResistance, BlastResistance, BleedResistance, IronSkin, Earplugs, Windproof, TremorResistance, Dungmaster, EffluvialExpert, HeatGuard, AttackBoost, DefenseBoost, HealthBoost, RecoveryUp, RecoverySpeed, FireResistance, WaterResistance, IceResistance, ThunderResistance, DragonResistance, BlightResistance, FireAttack, WaterAttack, IceAttack, ThunderAttack, DragonAttack, PoisonAttack, ParalysisAttack, SleepAttack, BlastAttack, NormalShots, PiercingShots, SpreadPowerShots, FreeElemAmmoUp, CritEye, CritBoost, WeaknessExploit, Focus, PowerProlonger, Handicraft, CritDraw, Partbreaker, Slugger, StaminaThief, MasterMounter, Airborne, LatentPower, Agitator, PeakPerformance, Heroics, Fortify, Resentment, Resuscitate, HornMaestro, CapacityBoost, SpecialAmmoBoost, Artillery, HeavyArtillery, MarathonRunner, Constitution, LeapOfFaith, StaminaSurge, HungerResistance, EvadeWindow, EvadeExtender, Guard, QuickSheath, Widerange, ItemProlonger, FreeMeal, SpeedEating, SpeedSharpening, Bombardier, Mushroomancer, MasterFisher, ProTransporter, MasterGatherer, HoneyHunter, CarvingPro, DivineBlessing, PalicoRally, Botanist, Geologist, MaxMight, SlingerCapacity, Stealth, FlinchFree, ScoutFlyRangeUp, SpeedCrawler, JumpMaster, SurvivalExp, AquaticMob, CliffHanger, Blindsider, Scholar, Entomologist, EffluviaResistance, Scenthound, ForagerLuck, Detector, BbqMaster, ToolSpecialist, AffinitySliding, Intimidator, HastenRecovery, SuperRecovery, PoisonDurationUp, Adrenaline, StaminaCapUp, CritElement, MindEye, Bludgeoner, NonElementalBoost, CaptureMaster, GuardUp, Guts, MasterTouch, NullWind, RazorSharp, CritStatus, GoodLuck, BowChargePlus, PunishingDraw, ProtectivePolish, PoisonFunc, ParaFunc, SleepFunc, BlastFunc, EldersealBoost, GreatLuck, CarvingMaster, ElementalAirborne, IgniIntensity];
export const SkillIcons = [];


for (let i = 0; i < skills.length; i++) {
    SkillIcons.push({id: i+1, icon: skills[i]})
}